### ISSUE TITLE
Presentation of <product_ ... information

### ISSUE THREAD

**Issue by axelssonHakan** [dingusdk/haihc#2]
1. In the UI the ihcid is presented as decimal but in the proj file its hex. Not sure how the presentation is in the ihc client (ord software)
2. In "my" proj file (ELKO/ELJO) there is a attribute for position that would be very nice to get displayed in the UI as well

**Comment by dingusdk** [comment]
In the soap requests the ihcid is integer. I only use the hex represantation when it has something to do with the project files where the ihcid is hex.
I will look into the position attribute, I have not used it myself, but I guess it is also there in LK project. If it is there I will add it. (I will leave this issue open until I have checked)

**Comment by dingusdk** [comment]
I have added the "position" from the ihc project to be show with the other ihc info.
