### ISSUE TITLE
Can't get the component running

### ISSUE THREAD

**Issue by donnib** [dingusdk/haihc#3]
Hi,
I am trying to help a colleague to get his IHC installation in HASS and we run into issues, here is the log file. The problem is seen at line 150.

Any ideas what the problem might be ? He did upgrade his IHC controller to latest version. 

/donnib
[home-assistant.log](https://github.com/dingusdk/haihc/files/1578525/home-assistant.log)

**Comment by donnib** [comment]
@dingusdk Any ideas ?

**Comment by axelssonHakan** [comment]
Nothing much to go on here.

- Have you copied all the components to the `/home/homeassistant/haihc/custom_components`?
- Are you using auto_setup?

**Comment by donnib** [comment]
@axelssonHakan Yes to both questions. As mentioned we just see the component crash at startup as you can see in the log file.

**Comment by dingusdk** [comment]
The "Crash" is because the project file fails to download from the IHC controlller. It looks like the authentication is ok because there is no errors before. 
Do you have the correct version 2.1.0 (or later) of ihcsdk? If downloaded automatically by home assistant it is placed in the folder: <homassistant_config_folder>/deps/PythonXX/site-packages
Can you get a connection to the controller using my "Alternative service view"? 
http://www.dingus.dk/updated-ihc-alternative-service-view/
If this also fails - could it be a permission issue - do the IHC user have all permissions set?

**Comment by donnib** [comment]
Ok so i passed this error now by starting from scratch and now i get following : 

`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/setup.py", line 199, in _async_setup_component
    component.setup, hass, processed_config)
  File "/usr/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ihc/__init__.py", line 123, in setup
    setup_service_functions(hass, ihc_controller)
  File "/config/custom_components/ihc/__init__.py", line 203, in setup_service_functions
    schema=SET_RUNTIME_VALUE_BOOL_SCHEMA)
TypeError: register() got multiple values for argument 'schema'`

I attached my project 
[Test.zip](https://github.com/dingusdk/haihc/files/1661751/Test.zip)

And yes your Alternative Service View works fine, i have enabled all permissions i could.

UPDATE: I tried all sorts of things, such as uploading an empty project to the controller, using a project which works for a colleague, rebooted the controller, none solve the problem

@dingusdk maybe you have an idea what could be wrong ?

**Comment by plazmdk** [comment]
I just had the same issue - It seems that the component is not upgraded to support the new 0.60.x as a downgrade to 0.59.2 made it work again.

@dingusdk does this sound correct?

**Comment by donnib** [comment]
@plazmdk it may be right, i am using 0.61.1 so that could be the problem.

**Comment by dingusdk** [comment]
HA Version 0.61 made some changes for registering services - I have updated haihc 2.1.1 so it should be working now with HA 0.61
Note from the next version HA 0.62 the IHC integration should be included so you no longer need the custom component. If you want to try it out before it is released you can get it from github now.

**Comment by donnib** [comment]
@dingusdk Yes i am aware of that the PR has been approved, it's just before it get's approved i am playing around with it. 

Btw i was confused by the fact that you write `host` in the documentation in stead or `url`, isn't this a typo in the doc ? https://github.com/home-assistant/home-assistant.github.io/pull/4129/files#diff-ba04f71e57e96f0a36f3a621ac4fb65aR24

**Comment by dingusdk** [comment]
Yes it should be `url` (it was host at the beginning, but I change it to match what other components are doing)
I will change it and make a new PR and hope it can be merged before release 0.62
Thank you for finding this
