### ISSUE TITLE
Home Assistant stops getting the events

### ISSUE THREAD

**Issue by WoodsterDK** [dingusdk/haihc#5]
Hi Dingus,

I have experienced on 6.1HW that HA stops responding on button presses - but if I restart HA, then the connection is back to the IHC controller.

I'm not running the latest official version, but haven't seen a change that involves stability.
Any ideas?

**Comment by dingusdk** [comment]
I am aware of this. If the connection is lost from HA to the IHC controller or you reboot  the controller or update the project on the controller this can happen.
I will try to improve on the re-connection when this happens, and let you know here.

**Comment by donnib** [comment]
@dingusdk that would be cool, i also seem something related to this.

**Comment by WoodsterDK** [comment]
Sounds great.

**Comment by dingusdk** [comment]
I have made an update to the ihcsdk that should improve on the re-connect if the ihc controller is reset or the connection is lost from HA
If you want to try it out you can update the ihcsdk manually to version 2.2.0:

`pip3 install --upgrade ihcsdk`

And you need to to this is the same context as HA - in case you are using a virtual python environment. You should have HA stopped while you do this

**Comment by WoodsterDK** [comment]
Excellent - will give it a go...

**Comment by donnib** [comment]
@dingusdk it would be nice if you would make a PR for this so it goes into next version of HASS. Could you do that please ?

**Comment by dingusdk** [comment]
I have just made the PR

**Comment by WoodsterDK** [comment]
I think it has reached the released version. It seems to be working. Thanjs.

**Comment by WoodsterDK** [comment]
Thanks☺
